Add Centrifuge governance
nova-wallet/nova-utils pull request #1379
Opened 2023-03-15 10:05 UTC by leohar

2023-03-15 10:11 UTC, stepanLav approved these changes

2023-03-16 07:25 UTC, stepanLav approved these changes

2023-03-16 07:25 UTC, stepanLav commented
I forgot that I've already approved 😅

2023-03-16 09:18 UTC, valentunn requested changes
Please inlcude it to v9 as well once merged

2023-03-17 08:28 UTC, valentunn approved these changes

2023-03-17 09:42 UTC, merged