Temporary remove Crab2 network
nova-wallet/nova-utils pull request #1384
Opened 2023-03-16 08:02 UTC by stepanLav

2023-03-16 09:17 UTC, valentunn approved these changes

2023-03-16 09:19 UTC, valentunn requested changes
Please inlclude this to v9 as well

2023-03-16 13:42 UTC, ERussel approved these changes

2023-03-17 04:31 UTC, leohar approved these changes

2023-03-17 08:28 UTC, valentunn approved these changes

2023-03-17 08:40 UTC, merged