Add Exosama network
nova-wallet/nova-utils pull request #1461
Opened 2023-03-29 08:47 UTC by leohar

**Exosama network specs**
<img width="300" alt="image" src="https://user-images.githubusercontent.com/16337578/228477882-9c105bfc-7fef-47c7-aa40-a197be9f0d5c.png">

<img width="600" alt="image" src="https://user-images.githubusercontent.com/16337578/228477544-841f5be0-f019-4e9d-95d0-3db6a38247cf.png">

**MOONSAMA(SAMA) token specs https://explorer.exosama.com/token/0x8C992cba48189a79204223d106fCB1D797A5F87a/token-transfers
[Token ticker and price](https://www.coingecko.com/en/coins/moonsama/historical_data#panel)

2023-03-29 09:13 UTC, valentunn requested changes

2023-03-29 09:13 UTC, valentunn commented on chains/v9/chains_dev.json
> +                    "type": "exosama",
etherscan?

2023-03-29 09:56 UTC, leohar commented on chains/v9/chains_dev.json
> +                    "type": "exosama",
done

2023-03-30 08:33 UTC, valentunn approved these changes

2023-03-30 08:40 UTC, merged