Adding new polkadot parachains
nova-wallet/nova-utils pull request #226
Opened 2022-03-15 08:07 UTC by stepanLav

2022-03-15 08:35 UTC, valentunn requested changes
Interlay uses orml

2022-03-15 09:54 UTC, stepanLav commented
> Interlay uses orml

fixed!

2022-03-15 16:34 UTC, antonkhvorov commented on chains/v2/chains_dev.json
> +                "symbol": "INTERBTC",
yes, I agree — interBTC is the right name based on Interlay website

2022-03-16 12:10 UTC, antonkhvorov commented on chains/v2/chains_dev.json
> +                "symbol": "interBTC",
"priceId": "bitcoin"

2022-03-16 12:12 UTC, stepanLav commented on chains/v2/chains_dev.json
> +                "symbol": "interBTC",
fixed

2022-03-16 12:13 UTC, antonkhvorov approved these changes

2022-03-16 12:19 UTC, stepanLav commented
> Interlay uses orml

Could you resolve your change request?

2022-03-16 12:25 UTC, valentunn approved these changes

2022-03-16 12:31 UTC, merged