Adding aUSD and change kUSD
nova-wallet/nova-utils pull request #287
Opened 2022-04-12 08:14 UTC by stepanLav

2022-04-12 11:20 UTC, stepanLav commented
## Android ✅

<details>
  <summary>Parallel Heiko</summary>

<img width="499" alt="Screenshot 2022-04-12 at 14 17 46" src="https://user-images.githubusercontent.com/40560660/162948781-32779b74-5fab-4e68-98bd-b8537856540f.png">


</details>

<details>
  <summary>Karura</summary>

<img width="499" alt="Screenshot 2022-04-12 at 14 17 40" src="https://user-images.githubusercontent.com/40560660/162948885-c09c5498-4549-49c5-9408-a74e65c00a92.png">


</details>

<details>
  <summary>Bifrost</summary>

<img width="499" alt="Screenshot 2022-04-12 at 14 17 27" src="https://user-images.githubusercontent.com/40560660/162949006-d2fccff6-37c6-4039-9513-9ac6ad1fb2c3.png">


</details>

2022-04-12 11:23 UTC, stepanLav commented
## iOS ✅

<details>
  <summary>Parallel Heiko</summary>

<img width="551" alt="Screenshot 2022-04-12 at 14 21 25" src="https://user-images.githubusercontent.com/40560660/162949412-b6139a40-e8b8-46d9-9143-2c6b89790343.png">

</details>

<details>
  <summary>Karura</summary>

<img width="551" alt="Screenshot 2022-04-12 at 14 21 20" src="https://user-images.githubusercontent.com/40560660/162949439-a56d9730-78c5-42af-9618-0669138f3671.png">

</details>

<details>
  <summary>Bifrost</summary>

<img width="551" alt="Screenshot 2022-04-12 at 14 21 08" src="https://user-images.githubusercontent.com/40560660/162949483-8d226785-f664-44a5-ac03-9464dac13aa2.png">


</details>

2022-04-13 04:47 UTC, valentunn requested changes
I suggest to leave kUSd on Heiko as it is to avoid problems if cKSM will be distributed. 
Specifically considering that kUSD on Heiko has only 3.7 kUSD upply

2022-04-15 12:10 UTC, antonkhvorov commented
Let's close that one due to switch to v3

2022-04-15 12:10 UTC, closed without merging