Add Kylin Darwinia Kapex networks
nova-wallet/nova-utils pull request #834
Opened 2022-09-21 14:20 UTC by leohar

<details>
  <summary> Kylin </summary>

<img width="637" alt="image" src="https://user-images.githubusercontent.com/16337578/191529361-c7a3e02b-48c4-452a-9a0d-9d9ca16a369c.png">

</details>
<details>
  <summary> Darwinia </summary>

<img width="626" alt="image" src="https://user-images.githubusercontent.com/16337578/191529475-115d59be-044e-46bf-b3ec-377b388d30b3.png">

</details>
<details>
  <summary> Kapex </summary>

<img width="646" alt="image" src="https://user-images.githubusercontent.com/16337578/191529262-e4036a3e-828d-4107-852f-bb7e73c93b5e.png">

</details>

2022-09-26 04:42 UTC, ERussel requested changes

2022-09-26 04:42 UTC, ERussel commented on chains/v5/chains_dev.json
> +            "url": "https://raw.githubusercontent.com/nova-wallet/nova-utils/master/chains/v2/types/unique.json",
Looks like a typo? Should be kylin.json

2022-09-26 06:43 UTC, leohar commented on chains/v5/chains_dev.json
> +            "url": "https://raw.githubusercontent.com/nova-wallet/nova-utils/master/chains/v2/types/unique.json",
sure, fixed

2022-09-27 07:02 UTC, ERussel approved these changes

2022-09-27 07:03 UTC, valentunn approved these changes

2022-09-27 08:31 UTC, merged